# service-master.yaml
apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: locust
spec:
  type: ClusterIP
  selector:
    app: locust-master
  ports:
    - name: web
      port: 8089
      targetPort: 8089
    - name: master-rpc
      port: 5557
      targetPort: 5557
